import type { Metadata } from "next";
import { Inter, Inter_Tight } from "next/font/google";
import "./globals.css";

const interTight = Inter_Tight({
    weight: ["500"],
    subsets: ["latin"],
    display: "block",
    variable: "--font-inter-tight",
});

const inter = Inter({
    weight: ["400", "500", "600"],
    subsets: ["latin"],
    display: "block",
    variable: "--font-inter",
});

export const metadata: Metadata = {
    title: "AutoHub",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                {/* Description no longer than 155 characters */}
                <meta
                    name="description"
                    content="AutoHub - Electrical Cars Website"
                />

                {/* Product Name */}
                <meta
                    name="product-name"
                    content="AutoHub - Electrical Cars Website"
                />

            </head>
            <body
                className={`${inter.variable} ${interTight.variable} bg-white font-sans text-paragraph font-medium text-g-500 antialiased md:text-body`}
            >
                {children}
            </body>
        </html>
    );
}
